spring:
  application:
    name: pickTime

  config:
    import: "optional:classpath:application-secret.yml"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${datasource.url}/picktime?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: ${datasource.username}
    password: ${datasource.password}
    hikari:
      pool-name: hikari-pool

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      host: ${mongodb.host}
      port: ${mongodb.port}
      authentication-database: admin
      username: ${mongodb.username}
      password: ${mongodb.password}
      database: ${mongodb.database}